config/routes.rb
Rails.application.routes.draw do
  devise_for :parents
  resources :parents
  resources :kids
  
  
  root 'parents#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
  belongs_to :parent
  belongs_to :kid
end

app/models/kid.rb
class Kid < ApplicationRecord
    has_many :families
    has_many :parents, through: :families
    accepts_nested_attributes_for :families
    
    def family_id
        if families.empty?
            "(none)"
        else
            families.parent_id
        end
    end


end


#from doggie daycare app
# class Dog < ActiveRecord::Base
#   belongs_to :vet
#   has_many :custodies
#   has_many :owners, :through => :custodies
#   accepts_nested_attributes_for :custodies

#   def last_name
#     if custodies.empty?
#       "(none)"
#     else
#       custodies.first.owner.last_name
#     end
#   end
  
# end

app/models/parent.rb
class Parent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
    
    has_many :families
    has_many :kids, through: :families
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
    #below adapted from doggie daycare
    #@kid.families.build
  end

  # GET /kids/1/edit
  def edit
        #adapted from doggie daycare
    @kid.families.build
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      #below was original. second was adpated from doggie daycare
      #params.require(:kid).permit(:name, :grade)
      params.require(:kid).permit(:name, :grade, families_attributes: [:id, parent_id, :_destroy])
    end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :authenticate_parent!
  #before_action :set_parent, only: [:show, :edit, :update, :destroy]
  before_action :set_parent, only: [:edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
    #@parent = Parent.find(params[:id])
    @parent = Parent.find(current_parent.id)
    @kids = Kid.all
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])    
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/kids/_form.html.erb
<%= form_with(model: kid, local: true) do |form| %>
  <% if kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :kid_name %>
  </div>

  <div class="field">
    <%= form.label :grade %>
    <%= form.text_field :grade, id: :kid_grade %>
  </div>
  
  <!--copied in and adapted from the mousy app-->
  <div class="field">
      <%= form.text_field :parent_id, value: current_parent.id %>
  </div>
  
  <!--copied in adapted from doggie daycare lesson notes-->
    <%= form.simple_fields_for(:families) do |family_fields| %>
      <%= family_fields.association :parent_id %>
     
     
      <%# Only show the destroy checkbox if a record is already saved %>
      <!--< % if custody_fields.object.persisted? %>-->
      <!--  < %= custody_fields.input :_destroy, as: :boolean %>-->
      <!--< % end %>-->
    <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kids</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.grade %></td>
        <td><%= link_to 'Show', kid %></td>
        <td><%= link_to 'Edit', edit_kid_path(kid) %></td>
        <td><%= link_to 'Destroy', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kid', new_kid_path %>

app/views/kids/new.html.erb
<h1>New Kid</h1>

<%= render 'form', kid: @kid %>

<%= link_to 'Back', parent_path(current_parent.id) %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @kid.grade %>
</p>

<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schoolbus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/parents/_form.html.erb
<%= form_with(model: parent, local: true) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :parent_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= link_to 'Show', parent_path(parent) %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>
<br>
<p>
  <strong><%= link_to 'Add a kid', new_kid_path %></strong>
</p>

<p>
  All kids for this parent
</p>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Grade</th>
      </tr>
    </thead>
    <tbody>
      <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.grade %></td>
        <!--<td>< %= link_to 'Show', parent_path(parent) %></td>-->
        <!--<td>< %= link_to 'Edit', edit_parent_path(parent) %></td>-->
        <!--<td>< %= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
      </tbody>
  </table>
  



<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>